"""init model

Revision ID: 0b5b33d55ff0
Revises: 
Create Date: 2024-05-09 22:17:41.696438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b5b33d55ff0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foreign_passport_rf',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('first_name_latin', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('last_name_latin', sa.String(), nullable=False),
    sa.Column('second_name', sa.String(), nullable=True),
    sa.Column('citizenship', sa.String(length=50), nullable=False),
    sa.Column('citizenship_latin', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('birth_place', sa.String(length=255), nullable=False),
    sa.Column('birth_place_latin', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('issued_by', sa.String(length=255), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passport_rf',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('series', sa.String(length=4), nullable=False),
    sa.Column('number', sa.String(length=6), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('second_name', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('birth_place', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('issued_by', sa.String(length=255), nullable=False),
    sa.Column('division_code', sa.String(length=10), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('registration_address', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('passport_rf_id', sa.Uuid(), nullable=True),
    sa.Column('foreign_passport_rf_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['foreign_passport_rf_id'], ['foreign_passport_rf.id'], onupdate='SET NULL'),
    sa.ForeignKeyConstraint(['passport_rf_id'], ['passport_rf.id'], onupdate='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('client',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=48), nullable=False),
    sa.Column('client_private_secret', sa.String(), nullable=False),
    sa.Column('client_id_issued_at', sa.BigInteger(), nullable=False),
    sa.Column('client_secret_expires_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_client_id'), 'client', ['client_id'], unique=True)
    op.create_table('token_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_id', sa.String(length=48), nullable=False),
    sa.Column('token_type', sa.String(length=40), nullable=False),
    sa.Column('refresh_token', sa.String(length=48), nullable=False),
    sa.Column('issued_at', sa.BigInteger(), nullable=False),
    sa.Column('refresh_token_revoked_at', sa.BigInteger(), nullable=True),
    sa.Column('expires_in', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_session_refresh_token'), 'token_session', ['refresh_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_session_refresh_token'), table_name='token_session')
    op.drop_table('token_session')
    op.drop_index(op.f('ix_client_client_id'), table_name='client')
    op.drop_table('client')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('passport_rf')
    op.drop_table('foreign_passport_rf')
    # ### end Alembic commands ###
